//try catch

try{
    console.log('Start of try');
    blalalala();
    console.log('End of try');
}catch(error){
    // console.log('Error has occurred');
    console.log(error);
}